#pragma once

enum DIRECTION { DIR_LEFT, DIR_TOP, DIR_RIGHT, DIR_BOTTOM, DIR_END };

enum OBJID {OBJ_PLAYER, OBJ_BULLET, OBJ_MONSTER, OBJ_MOUSE, OBJ_END };

enum UIID {UI_CLOUD, UI_LIFE, UI_PLAYERHP, UI_MONSTERHP, UI_END };