#pragma once

enum DIRECTION { DIR_LEFT, DIR_TOP, DIR_RIGHT, DIR_BOTTOM, DIR_END };

enum OBJID {OBJ_PLAYER, OBJ_BULLET, OBJ_MONSTER, OBJ_MOUSE, OBJ_ITEM, OBJ_END }; //OBJ_ITEM

enum ITEMID {ITEM_POWER, ITEM_SHIELD, ITEM_BOMB, ITEM_END};